name: Daily ECMWF Maps (Playwright Debug)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # 05:00 UTC (~06/07:00 Europe/Rome depending on DST)

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright (Chromium) deps
        run: |
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run map downloader (Playwright debug)
        run: |
          python download_maps_playwright_debug.py

      - name: Compute today date (Europe/Rome)
        id: today
        run: echo "today=$(TZ=Europe/Rome date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - name: Send email (if at least one map exists)
        if: ${{ hashFiles('maps/*.png') != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          secure: true
          to: ${{ secrets.RECIPIENTS }}
          from: ${{ secrets.SMTP_FROM }}
          subject: "Daily ECMWF Maps $(date +'%d-%m-%Y')"
          body: |
            In allegato le mappe ECMWF (EFI TP 99° quantile).
            Se qualcosa fallisce, scarica l'artifact 'ecmwf-maps-${{ github.run_id }}' per i dettagli (HTML e PNG).
          attachments: |
            maps/map_day1.png
            maps/map_day2.png
            maps/map_day3.png
