name: Daily ECMWF Maps (Playwright)

on:
  schedule:
    - cron: "0 7 * * *" # ogni giorno alle 07:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: Download ECMWF maps screenshots
        id: download_maps
        run: python download_maps_playwright.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          secure: true
          to: ${{ secrets.RECIPIENTS }}
          from: ${{ secrets.SMTP_FROM }}
          subject: "Daily ECMWF Maps – $(date +'%Y-%m-%d')"
          body: "In allegato le mappe ECMWF per i prossimi 3 giorni (EFI TP 99° quantile)."
          attachments: |
            maps/map_day1.png
            maps/map_day2.png
            maps/map_day3.png
